- name: Working with the newly created hosts
  hosts: gcp_instances
  become: true
  roles:
  - role: nginxinc.nginx
  vars:
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
    nginx_type: opensource
    nginx_enable: true
  tasks:
  - name: Replace default html page
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html
      owner: root
      group: root
      mode: 0644

