- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    gcp_auth_kind: serviceaccount
    gcp_zone: "us-central1-a"
    gcp_region: "us-central1"
    gcp_ssh_key: "{{ lookup('file', '~/.ssh/google_compute_engine.pub') }}"

  tasks:
  - name: Create a disk
    gcp_compute_disk:
      name: 'ansible-disk-instance'
      size_gb: 50
      source_image: 'projects/centos-cloud/global/images/family/centos-7'
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_auth_kind }}"
      service_account_file: "{{ gcp_auth_file }}"
      state: present
    register: disk
  - name: Create a network
    gcp_compute_network:
      name: 'ansible-network-vpc'
      auto_create_subnetworks: true
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_auth_kind }}"
      service_account_file: "{{ gcp_auth_file }}"
      state: present
    register: network
  - name: Create an address
    gcp_compute_address:
      name: 'ansible-address-instance'
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_auth_kind }}"
      service_account_file: "{{ gcp_auth_file }}"
      state: present
    register: address
  - name: Create a firewall rule
    gcp_compute_firewall:
      name: 'ansible-firewall-rule'
      allowed:
      - ip_protocol: tcp
        ports:
        - '22'
        - '80'
        - '443'
      network: "projects/{{ gcp_project }}/global/networks/ansible-network-vpc"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_auth_kind }}"
      service_account_file: "{{ gcp_auth_file }}"
      state: present
    register: address
  - name: Create an instance
    gcp_compute_instance:
      name: ansible-test-vm
      machine_type: n1-standard-1
      disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
      network_interfaces:
      - network: "{{ network }}"
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      tags:
        items:
        - http-server
        - https-server
      metadata:
        items:
        - key: ssh-keys
          value: "gcpuser:{{ gcp_ssh_key }}"
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_auth_kind }}"
      service_account_file: "{{ gcp_auth_file }}"
      state: present
    register: instance

  - name: debug printing the ip address of the instance
    debug:
      msg: "{{ item }}"
    with_items:
    - "{{ instance }}"

  - name: Wait for SSH to come up
    wait_for: host={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} port=22 delay=10 timeout=60

  - name: Add host to groupname
    add_host: hostname={{ instance.networkInterfaces[0].accessConfigs[0].natIP }} groupname=gcp_instances

