---
- name: Working with the newly created host
  hosts: gcp_instances
  become: true
  roles:
    - role: nginxinc.nginx
  vars:
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
    nginx_type: opensource
    nginx_enable: true

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: URL to connect to the new nginx server
    debug:
      msg: "{{ item }}"
    with_items:
    - "Web Server: http://{{ instance.networkInterfaces[0].accessConfigs[0].natIP }}/"
    - "Console: ssh -i ~/.ssh/google_compute_engine {{ instance.networkInterfaces[0].accessConfigs[0].natIP }}"

